sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t langhaoz/fibcalc-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true langhaoz/fibcalc-test npm test -- --coverage

after_success:
    - docker build -t langhaoz/fibcalc-client ./client
    - docker build -t langhaoz/fibcalc-server ./server
    - docker build -t langhaoz/fibcalc-nginx ./nginx
    - docker build -t langhaoz/fibcalc-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push langhaoz/fibcalc-client
    - docker push langhaoz/fibcalc-server
    - docker push langhaoz/fibcalc-nginx
    - docker push langhaoz/fibcalc-worker

# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: us-east-2
#     app: Fibcalc
#     env: Fibcalc-env
#     bucket_name: elasticbeanstalk-us-east-2-330549758279
#     bucket_path: fibcalc
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
